### ISSUE TITLE
Fix family entry RF04034 (_2 label issue)

### ISSUE THREAD

**Issue by kalvari** [Rfam/rfam-family-pipeline#53]
This is a new entry for `MIR2118` (old Rfam entry RF01911). The family was not correctly committed to SVN repository due to the previous version. However a new was created in rfam_live. 

TO DO:

- [ ] Delete erroneous `RF04034` entry from the database
- [ ] Checkout `RF01911` from the SVN
- [ ] Replace old `RF01911` SEED with new MIR2118 from miRBase
- [ ] Rebuild and commit the new family

*Note: Potential candidate for merging SEEDs

**Comment by AntonPetrov** [comment]
RF04034 has been moved to `dead_family` so the SVN and RfamLive are in sync now. RF04185 was created for `MIR2118_2` and is due to be release in 14.6. Eventually RF0911 and RF04185 should be reviewed and potentially merged.

This problem should not happen again as a new QC will prevent families with the existing IDs from being added to the database.
